name: Unified Release

on:
  push:
    branches:
      - "alpha-*"
      - "beta-*"
      - latest
  workflow_dispatch:

jobs:
  determine-release-type:
    uses: homebridge/.github/.github/workflows/determine-release-type.yml@latest
    with:
      ref_name: ${{ github.ref_name }}

  update-version:
    needs: determine-release-type
    uses: ./.github/workflows/update-version-local.yml
    with:
      release_type: ${{ needs.determine-release-type.outputs.release_type }}

  publish-release:
    needs: [determine-release-type, update-version]
    uses: homebridge/.github/.github/workflows/publish-release.yml@latest
    with:
      release_type: ${{ needs.determine-release-type.outputs.release_type }}
      version: ${{ needs.update-version.outputs.version}}

  promote-branch:
    needs: [determine-release-type, publish-release]
    if: ${{ needs.determine-release-type.outputs.release_type != 'latest' && needs.determine-release-type.outputs.release_type != 'skip' }}
    uses: homebridge/.github/.github/workflows/promote-branch.yml@latest
    with:
      branch_name: ${{ needs.determine-release-type.outputs.branch_name }}
      release_type: ${{ needs.determine-release-type.outputs.release_type }}

  workflow-failure:
    if: failure()  # Only runs if any job above fails
    needs: [determine-release-type, update-version, publish-release, promote-branch]
    uses: homebridge/.github/.github/workflows/report-failure.yml@latest
    with:
      workflow_name: ${{ github.workflow }}
      job_name: ${{ github.job }}
      run_url: ${{ github.server_url }}/{{ github.repository }}/actions/runs/${{ github.run_id }}